run1: Truckloads.cpp main1.cpp
	g++ -o main.out -std=c++11 -O2 -Wall Truckloads.cpp main1.cpp
	./main.out

run2: Reverse.cpp main2.cpp
	g++ -o main.out -std=c++11 -O2 -Wall Reverse.cpp main2.cpp
	./main.out

run3: EfficientTruckloads.cpp main3.cpp
	g++ -o main.out -std=c++11 -O2 -Wall EfficientTruckloads.cpp main3.cpp
	./main.out